import React from "react";

export function MobileCosOneThing() {
  return (
    <section id="mobile-vousvous-onething" className="mobile-story-onething-section px-5 py-16">
      {/* 1. Header with Stroke Text + Divider */}
      <div className="mobile-story-onething-header mb-6">
        <h2 className="font-outfit font-bold text-[30px] tracking-[2.5px] uppercase m-0 leading-tight">
          <span
            style={{
              WebkitTextStrokeWidth: "1.5px",
              WebkitTextStrokeColor: "#7B7A77",
              color: "#190B00",
              paintOrder: "stroke fill",
            }}
          >
            ONE THING
          </span>
          <span className="text-[#fffdfa] ml-2">I LEARNED</span>
        </h2>
        <div className="w-full h-[1px] bg-[rgba(255,253,250,0.15)] mt-3" />
      </div>

      {/* 2. Narrative Reflection Copy */}
      <div className="flex flex-col gap-5 font-outfit text-[16px] text-[#8c827a] leading-relaxed">
        <p className="m-0">
          Designing for AI isn't about replacing familiar experiences.
        </p>

        <p className="m-0">
          It's about introducing intelligence only where it{" "}
          <strong className="font-bold text-[#fffdfa]">removes friction.</strong>
        </p>

        <div className="flex flex-col gap-2">
          <p className="m-0">
            The strongest moments in this project weren't generated by AI—they came from balancing human intuition with AI assistance.
          </p>
          <div className="flex flex-col gap-1 mt-1 text-[15px] text-[#8c827a]">
            <p className="m-0">/Gestures made discovery effortless</p>
            <p className="m-0">/Conversations made intent easier to express</p>
            <p className="m-0">/Personalisation transformed inspiration into something uniquely personal.</p>
          </div>
        </div>

        <p className="font-outfit font-bold text-[22px] leading-snug text-[#fffdfa] mt-2 m-0">
          That <span className="text-[#EE6C13]">balance</span> became the most valuable design lesson from this project.
        </p>
      </div>
    </section>
  );
}

export default MobileCosOneThing;
